### ISSUE TITLE
Error: Cannot find module 'cssnano'

### ISSUE THREAD

**Issue by adibarda** [haoliangyu/ngx-leaflet-starter#42]
Hi,
While running: npm run build I get the following error:
Error: Cannot find module 'cssnano'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/storm/dev/ngx-leaflet-starter/webpack/webpack.config.prod.js:63:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/storm/dev/ngx-leaflet-starter/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/storm/dev/ngx-leaflet-starter/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/home/storm/dev/ngx-leaflet-starter/node_modules/webpack/bin/convert-argv.js:107:15)

Can you please assist resolving this issue?
Thanks,
Adi

**Comment by haoliangyu** [comment]
Good catch. `cssnano` is not included in the `package.json`. I will update the code soon.

**Comment by haoliangyu** [comment]
Should be fixed by 273a274.
